sudo: false
language: cpp
services: docker
before_install:
    - docker build -t dev-image .
script:
    - docker run --rm -u $UID:$GROUPS  -v `pwd`:/development -t lhci /bin/bash -c "meson build"
    - docker run --rm -u $UID:$GROUPS  -v `pwd`:/development -t lhci /bin/bash -c "cd build && ninja test"
